### ISSUE TITLE
Please clarify how the ESP32 and RP2040 communicate

### ISSUE THREAD

**Issue by jasongaunt** [MDCservice/EsPiFF#1]
Hi MDC,

I really like the potential of this product, however it's not clear in the documentation (README) how the ESP32 and RP2040 will communicate with each other.

Ideally, there should be:

- A fast and low latency bus like SPI or I2C between them
- A way for the ESP32 to program the RP2040 (so OTA can be performed on both)

Kind regards,
Jason

**Comment by MDCservice** [comment]
Hi Jason,

sorry for have not stated this detail. I have to update the datasheet, and the description about the the communication between ESP32 and RP2040. Its shown in the schematic, but not everybody looks into that.

There are 2 possibilities, how the ESP32 and the RP2040 can communicate: first is SPI, what should be the fastest. Second is UART, what allows the use of Firmata on the RP2040 in its current form.  I have already asked the Firmata developers, if and when they could add SPI as an additional transport, as an option to UART. This is a work in progress, and today there is no release date for it. But we definitely work on it. 

The above are just 2 possibilities. With the use of an RTOS, like Nuttx, the RP2040 could emulate a SPI RAM, where a driver already exists. Or emulate an SDcard, an 74HC595, .....

**Comment by jasongaunt** [comment]
@MDCservice Much appreciated for the extra information, can't wait for these to be released.

I plan on using one to directly drive LCD panels with the RP2040 acting as a graphics accelerator, the aim being to be able to draw a full car dash cluster in real time 😄 

Marking this issue as resolved!
